### ISSUE TITLE
Panic error

### ISSUE THREAD

**Issue by angelorc** [lino-network/lino#343]
If I try to install, then

```
lino init
lino start
```

I will get this error

```
panic: failed to open open /home/angelo/.lino/prevstates/account: no such file or directory

goroutine 1 [running]:
github.com/lino-network/lino/app.(*LinoBlockchain).ImportFromFiles.func2(0xfc1d46, 0x7, 0xe05d60, 0xc00092c6c0)
	/home/angelo/go/src/github.com/lino-network/lino/app/app.go:753 +0x10fe
......
```

**Comment by xiaoxiaff** [comment]
@angelorc pls check out with our guidance. https://github.com/lino-network/testnets

**Comment by angelorc** [comment]
I don't want to sync the chain, I'd like to have a fresh chain in my pc for test some application

**Comment by xiaoxiaff** [comment]
@angelorc then you can set https://github.com/lino-network/lino/blob/89431e07a3b250deee52d4e178e268fa9aed39eb/cmd/lino/main.go#L26 to false manually then compile the code.

**Comment by angelorc** [comment]
ok it work. thanks
