### ISSUE TITLE
[Dependency-Error] Docker-Compose Build Failed at Step 7/16

### ISSUE THREAD

**Issue by aekazitt** [lino-network/lino#385]
First I tried to recreate the issue #351 which fails build at step 9/16
However I found an error on Step 7/16 as followed:
```
...
Step 7/16 : RUN dep ensure
 ---> Running in 98ad488deb16
could not find project Gopkg.toml, use dep init to initiate a manifest
```

This was an easy fix referenced from this golang-dep update:
`https://github.com/golang/dep/pull/342`

So I changed **_Dockerfile_lino_** to have one more run command which is `dep init`
```
...
14  
15  RUN dep init && dep ensure
16  
...
```

This however cause a dependency error as followed:
```
...
Step 7/16 : RUN dep init && dep ensure
 ---> Running in 5689e7af30b1
Importing configuration from glide. These are only initial constraints, and are further refined during the solve process.
init failed: unable to solve the dependency graph: Solving failure: No versions of github.com/tendermint/crypto met constraints:
        master: Could not introduce github.com/tendermint/crypto@master, as its subpackage github.com/tendermint/crypto/bcrypt does not contain usable Go code (*pkgtree.NonCanonicalImportRoot).. (Package is required by github.com/cosmos/cosmos-sdk@fedekunze/move-sim-operations.)
        release-branch.go1.11: Could not introduce github.com/tendermint/crypto@release-branch.go1.11, as its subpackage github.com/tendermint/crypto/bcrypt does not contain usable Go code (*pkgtree.NonCanonicalImportRoot).. (Package is required by github.com/cosmos/cosmos-sdk@fedekunze/move-sim-operations.)
```

**Comment by xiaoxiaff** [comment]
Thanks for the report and docker file in this repo is outdated. I will update the docker file later.

**Comment by Stumble** [comment]
Thanks for the report.

We have updated the dockerfile, see https://github.com/lino-network/lino/blob/master/Dockerfile. Also, you can:
```
make docker-up
```
It requires as least 32GB memory to start because it needs to import the whole state from the last upgrade and commit the whole state in the first block.
